import type {
  MockComment,
  MockConversation,
  MockFlaggedContent,
  MockModerationLogEntry,
  MockAutoReplyRule,
  MockDiscordServer,
  MockDiscordMessage,
} from './types';

export const MOCK_COMMENTS: MockComment[] = [
  {
    id: 'cmt-001',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    username: 'AlexStreams',
    platform: 'tiktok',
    commentText: 'This clip is absolute fire! 🔥 The clutch at the end had me screaming!',
    timestamp: '2024-07-22T14:32:00Z',
    sentiment: 'positive',
    status: 'new',
    likes: 342,
    postTitle: 'INSANE 1v5 Clutch in Overtime',
    postUrl: 'https://tiktok.com/@creator/video/123',
  },
  {
    id: 'cmt-002',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    username: 'SarahGaming',
    platform: 'youtube',
    commentText: 'Been following this channel for 2 years. Best content on the platform hands down.',
    timestamp: '2024-07-22T13:15:00Z',
    sentiment: 'positive',
    status: 'replied',
    likes: 156,
    postTitle: 'Funniest Rage Moment of the Stream',
    postUrl: 'https://youtube.com/watch?v=abc',
  },
  {
    id: 'cmt-003',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mike',
    username: 'MikeHatesEverything',
    platform: 'x',
    commentText: 'mid content tbh. seen better from smaller creators. ratio incoming',
    timestamp: '2024-07-22T12:45:00Z',
    sentiment: 'negative',
    status: 'new',
    likes: 23,
    postTitle: 'TikTok Behind the Scenes — Creator Meetup',
    postUrl: 'https://x.com/creator/status/456',
  },
  {
    id: 'cmt-004',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    username: 'EmmaPlays',
    platform: 'instagram',
    commentText: 'What headset are you using? The audio quality sounds amazing!',
    timestamp: '2024-07-22T11:20:00Z',
    sentiment: 'neutral',
    status: 'new',
    likes: 67,
    postTitle: 'Behind the scenes of my streaming setup',
    postUrl: 'https://instagram.com/p/789',
  },
  {
    id: 'cmt-005',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=troll1',
    username: 'RandomTroll42',
    platform: 'facebook',
    commentText: 'This is literally stolen content from [redacted]. Report this channel.',
    timestamp: '2024-07-22T10:55:00Z',
    sentiment: 'negative',
    status: 'flagged',
    likes: 5,
    postTitle: 'Podcast Hot Take Goes Viral',
    postUrl: 'https://facebook.com/creator/video/101',
  },
  {
    id: 'cmt-006',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jake',
    username: 'JakeTheSnake',
    platform: 'tiktok',
    commentText: 'Bro how do you hit shots like that?! Insane aim 🔥🎯',
    timestamp: '2024-07-22T09:10:00Z',
    sentiment: 'positive',
    status: 'new',
    likes: 891,
    postTitle: 'Keyboard Smash Rage Compilation',
    postUrl: 'https://tiktok.com/@creator/video/234',
  },
  {
    id: 'cmt-007',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa',
    username: 'Lisa_Creates',
    platform: 'instagram',
    commentText: 'Love the energy in this clip! Keep it up! 💜',
    timestamp: '2024-07-22T08:30:00Z',
    sentiment: 'positive',
    status: 'replied',
    likes: 234,
    postTitle: '$500 Donation Reaction — Priceless',
    postUrl: 'https://instagram.com/p/890',
  },
  {
    id: 'cmt-008',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chris',
    username: 'ChrisViews',
    platform: 'youtube',
    commentText: 'The editing on this is next level. What software do you use?',
    timestamp: '2024-07-22T07:45:00Z',
    sentiment: 'neutral',
    status: 'new',
    likes: 89,
    postTitle: 'Emotional Farewell to Old Setup',
    postUrl: 'https://youtube.com/watch?v=def',
  },
  {
    id: 'cmt-009',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hater1',
    username: 'TruthTeller99',
    platform: 'x',
    commentText: 'You fell off after the sponsorship deal. Sellout.',
    timestamp: '2024-07-22T06:15:00Z',
    sentiment: 'negative',
    status: 'flagged',
    likes: 12,
    postTitle: 'EPIC Fail Moment — You Had One Job',
    postUrl: 'https://x.com/creator/status/567',
  },
  {
    id: 'cmt-010',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nina',
    username: 'NinaPlays',
    platform: 'tiktok',
    commentText: 'Day 47 of asking for a face reveal 😂',
    timestamp: '2024-07-22T05:00:00Z',
    sentiment: 'positive',
    status: 'archived',
    likes: 1200,
    postTitle: 'Minecraft Hardcore Near-Death Experience',
    postUrl: 'https://tiktok.com/@creator/video/345',
  },
];

export const MOCK_CONVERSATIONS: MockConversation[] = [
  {
    id: 'conv-001',
    userName: 'David Miller',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    platform: 'instagram',
    lastMessage: 'Hey! I loved your latest stream. Would you be interested in a collab?',
    lastMessageTime: '2024-07-22T14:30:00Z',
    unread: true,
    messages: [
      {
        id: 'msg-001',
        conversationId: 'conv-001',
        senderName: 'David Miller',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
        platform: 'instagram',
        content: 'Hey! I loved your latest stream. Would you be interested in a collab?',
        timestamp: '2024-07-22T14:30:00Z',
        isOwn: false,
        read: false,
      },
    ],
  },
  {
    id: 'conv-002',
    userName: 'SponsorReach Agency',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sponsor',
    platform: 'youtube',
    lastMessage: 'We reviewed your proposal. Let us schedule a call this week.',
    lastMessageTime: '2024-07-22T12:10:00Z',
    unread: true,
    messages: [
      {
        id: 'msg-002a',
        conversationId: 'conv-002',
        senderName: 'SponsorReach Agency',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sponsor',
        platform: 'youtube',
        content: 'Hi, we saw your channel and love your content style!',
        timestamp: '2024-07-21T09:00:00Z',
        isOwn: false,
        read: true,
      },
      {
        id: 'msg-002b',
        conversationId: 'conv-002',
        senderName: 'You',
        senderAvatar: '',
        platform: 'youtube',
        content: 'Thanks! I would love to discuss potential partnership opportunities.',
        timestamp: '2024-07-21T09:45:00Z',
        isOwn: true,
        read: true,
      },
      {
        id: 'msg-002c',
        conversationId: 'conv-002',
        senderName: 'SponsorReach Agency',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sponsor',
        platform: 'youtube',
        content: 'We reviewed your proposal. Let us schedule a call this week.',
        timestamp: '2024-07-22T12:10:00Z',
        isOwn: false,
        read: false,
      },
    ],
  },
  {
    id: 'conv-003',
    userName: 'FanClub Jamie',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jamie',
    platform: 'tiktok',
    lastMessage: 'When is your next stream? I dont want to miss it! 🎮',
    lastMessageTime: '2024-07-21T22:15:00Z',
    unread: false,
    messages: [
      {
        id: 'msg-003a',
        conversationId: 'conv-003',
        senderName: 'FanClub Jamie',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jamie',
        platform: 'tiktok',
        content: 'When is your next stream? I dont want to miss it! 🎮',
        timestamp: '2024-07-21T22:15:00Z',
        isOwn: false,
        read: true,
      },
    ],
  },
  {
    id: 'conv-004',
    userName: 'TechReviewBot',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=techbot',
    platform: 'facebook',
    lastMessage: 'We would like to feature your setup in our next article.',
    lastMessageTime: '2024-07-21T16:50:00Z',
    unread: false,
    messages: [
      {
        id: 'msg-004a',
        conversationId: 'conv-004',
        senderName: 'TechReviewBot',
        senderAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=techbot',
        platform: 'facebook',
        content: 'Hi! We run a tech review blog. We would like to feature your setup in our next article.',
        timestamp: '2024-07-21T16:50:00Z',
        isOwn: false,
        read: true,
      },
      {
        id: 'msg-004b',
        conversationId: 'conv-004',
        senderName: 'You',
        senderAvatar: '',
        platform: 'facebook',
        content: "That sounds great! Let me know what details you'd need.",
        timestamp: '2024-07-21T17:20:00Z',
        isOwn: true,
        read: true,
      },
    ],
  },
];

export const MOCK_FLAGGED_CONTENT: MockFlaggedContent[] = [
  {
    id: 'flag-001',
    type: 'comment',
    content: 'This is literally stolen content from [redacted]. Report this channel.',
    reason: 'False claims / harassment',
    username: 'RandomTroll42',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=troll1',
    platform: 'facebook',
    date: '2024-07-22T10:55:00Z',
    status: 'pending',
  },
  {
    id: 'flag-002',
    type: 'comment',
    content: 'You fell off after the sponsorship deal. Sellout.',
    reason: 'Negative / toxic comment',
    username: 'TruthTeller99',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=hater1',
    platform: 'x',
    date: '2024-07-22T06:15:00Z',
    status: 'pending',
  },
  {
    id: 'flag-003',
    type: 'message',
    content: 'Hey DM me for free followers! Real and fast delivery 💯💯',
    reason: 'Spam / bot message',
    username: 'FollowerBoost',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=spammer',
    platform: 'instagram',
    date: '2024-07-21T19:45:00Z',
    status: 'pending',
  },
  {
    id: 'flag-004',
    type: 'comment',
    content: 'K*ll yourself streamer',
    reason: 'Violence / hate speech',
    username: 'DeletedUser789',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=deleted',
    platform: 'youtube',
    date: '2024-07-21T15:30:00Z',
    status: 'pending',
  },
];

export const MOCK_MODERATION_LOG: MockModerationLogEntry[] = [
  {
    id: 'log-001',
    action: 'deleted',
    target: 'Hate speech comment on Minecraft clip',
    targetType: 'comment',
    reason: 'Violates community guidelines — hate speech',
    moderator: 'Auto-mod',
    date: '2024-07-22T08:00:00Z',
  },
  {
    id: 'log-002',
    action: 'banned',
    target: 'SpamBot420',
    targetType: 'user',
    reason: 'Repeated spam across 5 posts',
    moderator: 'Auto-mod',
    date: '2024-07-22T07:30:00Z',
  },
  {
    id: 'log-003',
    action: 'approved',
    target: 'Criticism comment on sponsorship video',
    targetType: 'comment',
    reason: 'Legitimate constructive criticism',
    moderator: 'You',
    date: '2024-07-21T20:15:00Z',
  },
  {
    id: 'log-004',
    action: 'deleted',
    target: 'Link spam in DMs',
    targetType: 'message',
    reason: 'Phishing link detected',
    moderator: 'Auto-mod',
    date: '2024-07-21T18:45:00Z',
  },
  {
    id: 'log-005',
    action: 'ignored',
    target: 'Flagged comment on hot take post',
    targetType: 'comment',
    reason: 'Within acceptable opinion range',
    moderator: 'You',
    date: '2024-07-21T12:00:00Z',
  },
  {
    id: 'log-006',
    action: 'approved',
    target: 'Sponsorship question DM',
    targetType: 'message',
    reason: 'Legitimate business inquiry',
    moderator: 'You',
    date: '2024-07-20T16:30:00Z',
  },
];

export const MOCK_AUTO_REPLY_RULES: MockAutoReplyRule[] = [
  {
    id: 'rule-001',
    name: 'FAQ: Streaming Schedule',
    triggerType: 'faq',
    triggerKeywords: ['schedule', 'when stream', 'what time', 'next stream'],
    response:
      'Hey! 👋 I stream every Tuesday, Thursday, and Saturday at 7PM EST. Follow and turn on notifications to never miss a stream! 🎮',
    platform: 'all',
    enabled: true,
    usageCount: 452,
  },
  {
    id: 'rule-002',
    name: 'FAQ: Equipment Question',
    triggerType: 'faq',
    triggerKeywords: ['headset', 'keyboard', 'mouse', 'mic', 'setup', 'equipment', 'gear', 'pc specs'],
    response:
      "I use a full HyperX setup — Cloud Alpha headset, Alloy Origins keyboard, and Pulsefire Haste mouse. Full gear list in my bio link! 🎧⌨️",
    platform: 'all',
    enabled: true,
    usageCount: 328,
  },
  {
    id: 'rule-003',
    name: 'Negative Sentiment Response',
    triggerType: 'sentiment',
    triggerKeywords: [],
    response:
      "Thanks for your feedback! I'm always working to improve my content. If you have specific suggestions, drop them in my Discord! 💜",
    platform: 'all',
    enabled: false,
    usageCount: 0,
  },
  {
    id: 'rule-004',
    name: 'Sponsorship Inquiry Auto-Reply',
    triggerType: 'keyword',
    triggerKeywords: ['sponsor', 'brand deal', 'partnership', 'collab business'],
    response:
      'Thanks for reaching out about a potential partnership! Please email partnerships@ironcreator.com with your proposal and our team will get back to you within 48 hours. 📧',
    platform: 'all',
    enabled: true,
    usageCount: 89,
  },
  {
    id: 'rule-005',
    name: 'TikTok Collab Request',
    triggerType: 'keyword',
    triggerKeywords: ['collab', 'duet', 'stitch', 'make a video together'],
    response:
      "Always down for collabs! DM me on Discord with your idea and let's make something awesome together! 🔥",
    platform: 'tiktok',
    enabled: true,
    usageCount: 67,
  },
];

export const MOCK_DISCORD_SERVERS: MockDiscordServer[] = [
  {
    id: 'ds-001',
    name: 'Iron Creator Community',
    icon: 'https://api.dicebear.com/7.x/icons/svg?seed=iron',
    memberCount: 12847,
    channelCount: 28,
    connected: true,
    activityLevel: 'high',
  },
  {
    id: 'ds-002',
    name: 'Creator Collab Hub',
    icon: 'https://api.dicebear.com/7.x/icons/svg?seed=collab',
    memberCount: 5432,
    channelCount: 15,
    connected: true,
    activityLevel: 'medium',
  },
  {
    id: 'ds-003',
    name: 'Subscriber Lounge',
    icon: 'https://api.dicebear.com/7.x/icons/svg?seed=lounge',
    memberCount: 2156,
    channelCount: 10,
    connected: true,
    activityLevel: 'low',
  },
];

export const MOCK_DISCORD_MESSAGES: MockDiscordMessage[] = [
  {
    id: 'dm-001',
    serverId: 'ds-001',
    channelName: '#general-chat',
    username: 'NightOwlGamer',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nightowl',
    content: 'When is the next community game night? The last one was so fun! 🎮',
    timestamp: '2024-07-22T14:00:00Z',
    flagged: false,
  },
  {
    id: 'dm-002',
    serverId: 'ds-001',
    channelName: '#clips-feedback',
    username: 'SpeedDemon99',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=speed',
    content: 'Get free Discord nitro at totallylegitsite.notascam.com!!!',
    timestamp: '2024-07-22T13:45:00Z',
    flagged: true,
    flagReason: 'Spam / phishing link',
  },
  {
    id: 'dm-003',
    serverId: 'ds-001',
    channelName: '#memes',
    username: 'MemeLord420',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=memes',
    content: 'Check out this meme I made from the latest stream 😂',
    timestamp: '2024-07-22T13:30:00Z',
    flagged: false,
  },
  {
    id: 'dm-004',
    serverId: 'ds-002',
    channelName: '#collab-requests',
    username: 'PixelArtist',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pixel',
    content: 'Looking for streamers to collab on a charity event next month! DM me if interested.',
    timestamp: '2024-07-22T12:00:00Z',
    flagged: false,
  },
  {
    id: 'dm-005',
    serverId: 'ds-001',
    channelName: '#spam-corner',
    username: 'BotAccount555',
    userAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=bot555',
    content: '@everyone @everyone @everyone FREE GIVEAWAY CLICK HERE!!!',
    timestamp: '2024-07-22T11:15:00Z',
    flagged: true,
    flagReason: 'Mass ping / spam',
  },
];

export function getCommentById(id: string): MockComment | undefined {
  return MOCK_COMMENTS.find((c) => c.id === id);
}

export function getConversationById(id: string): MockConversation | undefined {
  return MOCK_CONVERSATIONS.find((c) => c.id === id);
}
