import type { CaptionProject, CaptionLine } from './types';

const SAMPLE_LINES: CaptionLine[] = [
  {
    id: 'line-001',
    speakerLabel: 'Speaker 1',
    startTime: '00:00.500',
    endTime: '00:02.300',
    text: "Oh my god, did you see that?!",
    emoji: '😱',
  },
  {
    id: 'line-002',
    speakerLabel: 'Speaker 1',
    startTime: '00:02.500',
    endTime: '00:04.800',
    text: "That was literally the most insane play I've ever made.",
    emoji: '🔥',
  },
  {
    id: 'line-003',
    speakerLabel: 'Speaker 2',
    startTime: '00:05.000',
    endTime: '00:06.200',
    text: 'No way. NO WAY!',
    emoji: '💀',
  },
  {
    id: 'line-004',
    speakerLabel: 'Speaker 1',
    startTime: '00:06.500',
    endTime: '00:09.000',
    text: 'Chat, clip that right now. This is going viral.',
  },
  {
    id: 'line-005',
    speakerLabel: 'Speaker 2',
    startTime: '00:09.200',
    endTime: '00:11.500',
    text: "I'm literally shaking. That was a 1v5 clutch in overtime!",
    emoji: '🏆',
  },
  {
    id: 'line-006',
    speakerLabel: 'Speaker 1',
    startTime: '00:12.000',
    endTime: '00:14.300',
    text: "Let's gooooo! This is why we grind!",
    emoji: '🚀',
  },
  {
    id: 'line-007',
    speakerLabel: 'Speaker 1',
    startTime: '00:14.500',
    endTime: '00:17.000',
    text: "I can't believe we pulled that off. Shoutout to the team.",
  },
  {
    id: 'line-008',
    speakerLabel: 'Speaker 2',
    startTime: '00:17.200',
    endTime: '00:20.000',
    text: 'Best moment of the stream, hands down.',
    emoji: '💯',
  },
];

export const MOCK_CAPTION_PROJECTS: CaptionProject[] = [
  {
    id: 'cap-001',
    clipId: 'clip-001',
    clipTitle: 'INSANE 1v5 Clutch in Overtime',
    thumbnailGradient: 'from-[#9146FF] via-[#6C5CE7] to-[#0A0A0F]',
    style: 'kinetic',
    language: 'English',
    wordCount: 87,
    status: 'generated',
    lines: SAMPLE_LINES,
    settings: {
      fontSize: 28,
      fontColor: '#FFFFFF',
      background: 'semi',
      position: 'bottom',
      animation: 'pop',
    },
    createdAt: '2026-07-20T14:30:00Z',
    updatedAt: '2026-07-20T14:32:00Z',
  },
  {
    id: 'cap-002',
    clipId: 'clip-002',
    clipTitle: 'Funniest Rage Moment of the Stream',
    thumbnailGradient: 'from-[#EF4444] via-[#F97316] to-[#0A0A0F]',
    style: 'emoji',
    language: 'English',
    wordCount: 24,
    status: 'applied',
    lines: [
      {
        id: 'line-r1',
        speakerLabel: 'Speaker 1',
        startTime: '00:00.300',
        endTime: '00:02.000',
        text: 'When the hitreg says NO 💀',
        emoji: '💀',
      },
      {
        id: 'line-r2',
        speakerLabel: 'Speaker 1',
        startTime: '00:02.200',
        endTime: '00:04.500',
        text: 'I shot him FIRST!',
        emoji: '😤',
      },
      {
        id: 'line-r3',
        speakerLabel: 'Speaker 1',
        startTime: '00:04.800',
        endTime: '00:06.000',
        text: 'I literally shot him in the head!',
        emoji: '🤬',
      },
    ],
    settings: {
      fontSize: 32,
      fontColor: '#FFD700',
      background: 'box',
      position: 'bottom',
      animation: 'slide',
    },
    createdAt: '2026-07-19T10:00:00Z',
    updatedAt: '2026-07-19T10:05:00Z',
  },
  {
    id: 'cap-003',
    clipId: 'clip-003',
    clipTitle: '$500 Donation Reaction — Priceless',
    thumbnailGradient: 'from-[#06B6D4] via-[#3B82F6] to-[#0A0A0F]',
    style: 'minimal',
    language: 'English',
    wordCount: 52,
    status: 'draft',
    lines: [
      {
        id: 'line-d1',
        speakerLabel: 'Speaker 1',
        startTime: '00:00.500',
        endTime: '00:02.000',
        text: 'Wait... is that a $500 donation?!',
        emoji: '😳',
      },
      {
        id: 'line-d2',
        speakerLabel: 'Speaker 1',
        startTime: '00:02.500',
        endTime: '00:05.000',
        text: "I don't know what to say... thank you so much.",
        emoji: '😭',
      },
      {
        id: 'line-d3',
        speakerLabel: 'Speaker 1',
        startTime: '00:05.500',
        endTime: '00:08.000',
        text: "This community is incredible. I'm literally crying.",
      },
    ],
    settings: {
      fontSize: 24,
      fontColor: '#E0E0E0',
      background: 'none',
      position: 'bottom',
      animation: 'fade',
    },
    createdAt: '2026-07-18T22:00:00Z',
    updatedAt: '2026-07-18T22:01:00Z',
  },
  {
    id: 'cap-004',
    clipId: 'clip-004',
    clipTitle: 'Emotional Farewell to Old Setup',
    thumbnailGradient: 'from-[#EC4899] via-[#F97316] to-[#0A0A0F]',
    style: 'bold',
    language: 'English',
    wordCount: 113,
    status: 'edited',
    lines: [
      {
        id: 'line-e1',
        speakerLabel: 'Speaker 1',
        startTime: '00:00.000',
        endTime: '00:03.500',
        text: "This setup has been with me for 5 years...",
        emoji: '🥹',
      },
      {
        id: 'line-e2',
        speakerLabel: 'Speaker 1',
        startTime: '00:03.800',
        endTime: '00:08.000',
        text: "From 0 subscribers to where we are today. It's been a journey.",
      },
      {
        id: 'line-e3',
        speakerLabel: 'Speaker 1',
        startTime: '00:08.500',
        endTime: '00:12.000',
        text: 'Time for an upgrade, but these memories will last forever.',
        emoji: '❤️',
      },
    ],
    settings: {
      fontSize: 36,
      fontColor: '#FFFFFF',
      background: 'semi',
      position: 'center',
      animation: 'typewriter',
    },
    createdAt: '2026-07-17T16:00:00Z',
    updatedAt: '2026-07-18T09:30:00Z',
  },
  {
    id: 'cap-005',
    clipId: 'clip-007',
    clipTitle: 'EPIC Fail Moment — You Had One Job',
    thumbnailGradient: 'from-[#F97316] via-[#EF4444] to-[#0A0A0F]',
    style: 'emoji',
    language: 'English',
    wordCount: 18,
    status: 'applied',
    lines: [
      {
        id: 'line-f1',
        speakerLabel: 'Speaker 1',
        startTime: '00:00.000',
        endTime: '00:02.000',
        text: 'One job. ONE JOB. 💀',
        emoji: '💀',
      },
    ],
    settings: {
      fontSize: 40,
      fontColor: '#FF6B6B',
      background: 'box',
      position: 'center',
      animation: 'pop',
    },
    createdAt: '2026-07-16T12:00:00Z',
    updatedAt: '2026-07-16T12:03:00Z',
  },
  {
    id: 'cap-006',
    clipId: 'clip-010',
    clipTitle: 'TikTok Behind the Scenes — Creator Meetup',
    thumbnailGradient: 'from-[#333333] via-[#1A1A1A] to-[#0A0A0F]',
    style: 'kinetic',
    language: 'English',
    wordCount: 41,
    status: 'generated',
    lines: [
      {
        id: 'line-b1',
        speakerLabel: 'Speaker 1',
        startTime: '00:00.000',
        endTime: '00:02.500',
        text: 'When you run into your favorite creator...',
        emoji: '😳',
      },
      {
        id: 'line-b2',
        speakerLabel: 'Speaker 2',
        startTime: '00:02.800',
        endTime: '00:05.000',
        text: 'Wait, you watch MY content?!',
        emoji: '🤯',
      },
      {
        id: 'line-b3',
        speakerLabel: 'Speaker 1',
        startTime: '00:05.300',
        endTime: '00:08.000',
        text: 'This is the best day of TwitchCon!',
        emoji: '🎉',
      },
    ],
    settings: {
      fontSize: 26,
      fontColor: '#FFFFFF',
      background: 'semi',
      position: 'bottom',
      animation: 'slide',
    },
    createdAt: '2026-07-15T20:00:00Z',
    updatedAt: '2026-07-15T20:04:00Z',
  },
];

export function getCaptionProjectById(id: string): CaptionProject | undefined {
  return MOCK_CAPTION_PROJECTS.find((c) => c.id === id);
}

export function getCaptionProjectsByClipId(clipId: string): CaptionProject[] {
  return MOCK_CAPTION_PROJECTS.filter((c) => c.clipId === clipId);
}
