import type { MockClip, MockMoment } from './types';

export const MOCK_CLIPS: MockClip[] = [
  {
    id: 'clip-001',
    title: 'INSANE 1v5 Clutch in Overtime',
    sourceStreamId: 'str-001',
    sourceStreamName: 'Late Night Valorant Ranked Grind',
    thumbnailGradient: 'from-[#9146FF] via-[#6C5CE7] to-[#0A0A0F]',
    duration: 30,
    format: 'vertical',
    momentType: 'clutch',
    momentConfidence: 94,
    momentTimestamp: '2:34:12',
    aiReasoning: 'Detected spike in chat activity (+340%) combined with loud audio peak and "CLUTCH" keyword frequency.',
    status: 'ready',
    views: 28400,
    engagement: 3200,
    caption: 'This 1v5 clutch in overtime had the whole chat going CRAZY 🔥',
    hashtags: ['#Valorant', '#Clutch', '#Gaming', '#FYP'],
  },
  {
    id: 'clip-002',
    title: 'Funniest Rage Moment of the Stream',
    sourceStreamId: 'str-001',
    sourceStreamName: 'Late Night Valorant Ranked Grind',
    thumbnailGradient: 'from-[#EF4444] via-[#F97316] to-[#0A0A0F]',
    duration: 15,
    format: 'vertical',
    momentType: 'funny',
    momentConfidence: 89,
    momentTimestamp: '1:15:45',
    aiReasoning: 'Detected laughter burst (+520% audio energy) followed by rapid chat emote spam. High shareability score.',
    status: 'published',
    views: 56200,
    engagement: 8900,
    caption: 'When the hitreg says NO 💀',
    hashtags: ['#Valorant', '#Funny', '#Rage', '#Gaming'],
  },
  {
    id: 'clip-003',
    title: '$500 Donation Reaction — Priceless',
    sourceStreamId: 'str-001',
    sourceStreamName: 'Late Night Valorant Ranked Grind',
    thumbnailGradient: 'from-[#06B6D4] via-[#3B82F6] to-[#0A0A0F]',
    duration: 30,
    format: 'vertical',
    momentType: 'donation',
    momentConfidence: 97,
    momentTimestamp: '3:02:18',
    aiReasoning: 'TTS donation alert detected, followed by emotional voice modulation and chat celebration. Perfect short-form moment.',
    status: 'published',
    views: 41500,
    engagement: 6200,
    caption: 'This donation reaction is EVERYTHING 😭❤️',
    hashtags: ['#Donation', '#Reaction', '#Wholesome'],
  },
  {
    id: 'clip-004',
    title: 'Emotional Farewell to Old Setup',
    sourceStreamId: 'str-002',
    sourceStreamName: 'Just Chatting — Reacting to Your Clips!',
    thumbnailGradient: 'from-[#EC4899] via-[#F97316] to-[#0A0A0F]',
    duration: 60,
    format: 'horizontal',
    momentType: 'emotional',
    momentConfidence: 92,
    momentTimestamp: '1:42:55',
    aiReasoning: 'Sentiment analysis detected emotional tone shift + slower speech cadence. Chat reaction overwhelmingly positive with heart emotes.',
    status: 'ready',
    views: 18900,
    engagement: 4500,
    caption: 'Saying goodbye to the setup that started it all 🥹',
    hashtags: ['#Emotional', '#Streamer', '#Goodbye'],
  },
  {
    id: 'clip-005',
    title: 'Chat Goes WILD After This Play',
    sourceStreamId: 'str-003',
    sourceStreamName: 'Elden Ring DLC — First Playthrough',
    thumbnailGradient: 'from-[#FF0000] via-[#CC0000] to-[#0A0A0F]',
    duration: 30,
    format: 'vertical',
    momentType: 'chat_reaction',
    momentConfidence: 86,
    momentTimestamp: '2:10:30',
    aiReasoning: 'Chat message velocity increased 5x in 3 seconds. Combined with "POG" and "WTF" keyword spikes and audio peak.',
    status: 'queued',
    views: 0,
    engagement: 0,
  },
  {
    id: 'clip-006',
    title: 'Boss Fight Victory After 47 Attempts',
    sourceStreamId: 'str-003',
    sourceStreamName: 'Elden Ring DLC — First Playthrough',
    thumbnailGradient: 'from-[#6C5CE7] via-[#EC4899] to-[#0A0A0F]',
    duration: 60,
    format: 'horizontal',
    momentType: 'victory',
    momentConfidence: 98,
    momentTimestamp: '3:28:15',
    aiReasoning: 'Sustained audio intensity peak + chat explosion with "FINALLY" and "LETS GO" patterns. Clear victory celebration detected.',
    status: 'rendering',
    views: 0,
    engagement: 0,
  },
  {
    id: 'clip-007',
    title: 'EPIC Fail Moment — You Had One Job',
    sourceStreamId: 'str-006',
    sourceStreamName: 'Apex Legends Ranked Push to Masters',
    thumbnailGradient: 'from-[#F97316] via-[#EF4444] to-[#0A0A0F]',
    duration: 15,
    format: 'square',
    momentType: 'fail',
    momentConfidence: 91,
    momentTimestamp: '0:45:22',
    aiReasoning: 'Sudden silence followed by laughter burst. Chat spamming "LUL" and "FAIL" emotes. High meme potential.',
    status: 'published',
    views: 72300,
    engagement: 12000,
    caption: 'One job. ONE JOB. 💀',
    hashtags: ['#ApexLegends', '#Fail', '#Funny', '#Gaming'],
  },
  {
    id: 'clip-008',
    title: 'Keyboard Smash Rage Compilation',
    sourceStreamId: 'str-001',
    sourceStreamName: 'Late Night Valorant Ranked Grind',
    thumbnailGradient: 'from-[#EF4444] via-[#6C5CE7] to-[#0A0A0F]',
    duration: 30,
    format: 'vertical',
    momentType: 'rage',
    momentConfidence: 95,
    momentTimestamp: '2:58:40',
    aiReasoning: 'Aggressive keyboard sounds + voice intensity spike + rapid cursor movement detected. Classic rage moment.',
    status: 'archived',
    views: 89200,
    engagement: 14500,
    caption: 'When the enemy team has aimbot... you SURE about that? 😤',
    hashtags: ['#Valorant', '#Rage', '#Gaming'],
  },
  {
    id: 'clip-009',
    title: 'New Subscriber Hype Train',
    sourceStreamId: 'str-002',
    sourceStreamName: 'Just Chatting — Reacting to Your Clips!',
    thumbnailGradient: 'from-[#53FC18] via-[#3AAD12] to-[#0A0A0F]',
    duration: 15,
    format: 'vertical',
    momentType: 'chat_reaction',
    momentConfidence: 87,
    momentTimestamp: '0:32:10',
    aiReasoning: 'Alert sound + chat velocity spike + subscriber notification overlay detected. High engagement pattern.',
    status: 'queued',
    views: 0,
    engagement: 0,
  },
  {
    id: 'clip-010',
    title: 'TikTok Behind the Scenes — Creator Meetup',
    sourceStreamId: 'str-005',
    sourceStreamName: 'TikTok LIVE — Behind the Scenes at TwitchCon',
    thumbnailGradient: 'from-[#333333] via-[#1A1A1A] to-[#0A0A0F]',
    duration: 30,
    format: 'square',
    momentType: 'funny',
    momentConfidence: 83,
    momentTimestamp: '0:18:30',
    aiReasoning: 'Group laughter detected + multiple voice sources + candid moment identified. Short-form optimized.',
    status: 'ready',
    views: 12100,
    engagement: 2300,
    caption: 'When you run into your favorite creator at TwitchCon 😂',
    hashtags: ['#TwitchCon', '#CreatorMeetup', '#BTS'],
  },
  {
    id: 'clip-011',
    title: 'Podcast Hot Take Goes Viral',
    sourceStreamId: 'str-007',
    sourceStreamName: 'Podcast — The Future of Creator Economy',
    thumbnailGradient: 'from-[#6B7280] via-[#4B5563] to-[#0A0A0F]',
    duration: 60,
    format: 'horizontal',
    momentType: 'chat_reaction',
    momentConfidence: 78,
    momentTimestamp: '0:42:15',
    aiReasoning: 'Heated debate segment with overlapping speech and increased tempo. Quote-worthy soundbite potential.',
    status: 'published',
    views: 34000,
    engagement: 5100,
    caption: 'This take on the creator economy is SPICY 🌶️',
    hashtags: ['#CreatorEconomy', '#Podcast', '#HotTake'],
  },
  {
    id: 'clip-012',
    title: 'Minecraft Hardcore Near-Death Experience',
    sourceStreamId: 'str-008',
    sourceStreamName: 'Minecraft Hardcore — Day 47',
    thumbnailGradient: 'from-[#FF0000] via-[#990000] to-[#0A0A0F]',
    duration: 30,
    format: 'vertical',
    momentType: 'clutch',
    momentConfidence: 90,
    momentTimestamp: '1:25:40',
    aiReasoning: 'Health bar critical + audio scream + quick inventory action detected. Classic clutch survival moment.',
    status: 'ready',
    views: 15600,
    engagement: 2800,
    caption: 'Half a heart. HALF. A. HEART. 😱',
    hashtags: ['#Minecraft', '#Hardcore', '#Clutch'],
  },
];

export const MOCK_MOMENTS: MockMoment[] = [
  {
    id: 'mom-001',
    streamId: 'str-001',
    streamTitle: 'Late Night Valorant Ranked Grind',
    momentType: 'clutch',
    confidence: 94,
    timestamp: '2:34:12',
    durationSuggestion: 30,
    thumbnailGradient: 'from-[#9146FF] via-[#6C5CE7] to-[#0A0A0F]',
    aiReasoning: 'Detected spike in chat activity (+340%) combined with loud audio peak and "CLUTCH" keyword frequency.',
    selected: true,
  },
  {
    id: 'mom-002',
    streamId: 'str-001',
    streamTitle: 'Late Night Valorant Ranked Grind',
    momentType: 'funny',
    confidence: 89,
    timestamp: '1:15:45',
    durationSuggestion: 15,
    thumbnailGradient: 'from-[#EF4444] via-[#F97316] to-[#0A0A0F]',
    aiReasoning: 'Detected laughter burst (+520% audio energy) followed by rapid chat emote spam. High shareability score.',
    selected: true,
  },
  {
    id: 'mom-003',
    streamId: 'str-001',
    streamTitle: 'Late Night Valorant Ranked Grind',
    momentType: 'donation',
    confidence: 97,
    timestamp: '3:02:18',
    durationSuggestion: 30,
    thumbnailGradient: 'from-[#06B6D4] via-[#3B82F6] to-[#0A0A0F]',
    aiReasoning: 'TTS donation alert detected, followed by emotional voice modulation and chat celebration.',
    selected: true,
  },
  {
    id: 'mom-004',
    streamId: 'str-001',
    streamTitle: 'Late Night Valorant Ranked Grind',
    momentType: 'rage',
    confidence: 95,
    timestamp: '2:58:40',
    durationSuggestion: 30,
    thumbnailGradient: 'from-[#EF4444] via-[#6C5CE7] to-[#0A0A0F]',
    aiReasoning: 'Aggressive keyboard sounds + voice intensity spike + rapid cursor movement detected.',
    selected: false,
  },
  {
    id: 'mom-005',
    streamId: 'str-001',
    streamTitle: 'Late Night Valorant Ranked Grind',
    momentType: 'victory',
    confidence: 88,
    timestamp: '3:55:20',
    durationSuggestion: 30,
    thumbnailGradient: 'from-[#6C5CE7] via-[#EC4899] to-[#0A0A0F]',
    aiReasoning: 'Match win screen detected + celebration audio + chat "GG" spam. Strong victory moment.',
    selected: true,
  },
  {
    id: 'mom-006',
    streamId: 'str-001',
    streamTitle: 'Late Night Valorant Ranked Grind',
    momentType: 'chat_reaction',
    confidence: 82,
    timestamp: '0:52:10',
    durationSuggestion: 15,
    thumbnailGradient: 'from-[#3B82F6] via-[#6C5CE7] to-[#0A0A0F]',
    aiReasoning: 'Chat velocity increasing during pre-game lobby. Banter and interaction peak detected.',
    selected: false,
  },
  {
    id: 'mom-007',
    streamId: 'str-001',
    streamTitle: 'Late Night Valorant Ranked Grind',
    momentType: 'fail',
    confidence: 76,
    timestamp: '1:32:45',
    durationSuggestion: 15,
    thumbnailGradient: 'from-[#F97316] via-[#EF4444] to-[#0A0A0F]',
    aiReasoning: 'Self-deprecating commentary + mild chat spam. Lower intensity but consistent moment pattern.',
    selected: false,
  },
  {
    id: 'mom-008',
    streamId: 'str-001',
    streamTitle: 'Late Night Valorant Ranked Grind',
    momentType: 'emotional',
    confidence: 85,
    timestamp: '4:05:30',
    durationSuggestion: 60,
    thumbnailGradient: 'from-[#EC4899] via-[#F97316] to-[#0A0A0F]',
    aiReasoning: 'End-of-stream speech detected. Sentiment shift to gratitude + slower speech cadence.',
    selected: true,
  },
];

export const MOCK_STREAMS_FOR_GENERATE = [
  { id: 'str-001', title: 'Late Night Valorant Ranked Grind', platform: 'twitch', duration: '4h 12m' },
  { id: 'str-003', title: 'Elden Ring DLC — First Playthrough', platform: 'youtube', duration: '3h 55m' },
  { id: 'str-006', title: 'Apex Legends Ranked Push to Masters', platform: 'twitch', duration: '5h 20m' },
];

export function getClipById(id: string): MockClip | undefined {
  return MOCK_CLIPS.find((c) => c.id === id);
}

export function getMomentsByStreamId(streamId: string): MockMoment[] {
  return MOCK_MOMENTS.filter((m) => m.streamId === streamId);
}
